PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bods:     <http://bods.openownership.org/vocabulary/>
PREFIX bods-res: <http://bods.openownership.org/resource/>

# This query returns the first 100 results for the statements added in September 2020
# (with interested parties which are entities)

SELECT ?parentName ?interest ?childName ?date
WHERE  {
    ?statement bods:hasInterestedParty ?parent .
    ?statement bods:hasSubject ?child .
    ?statement bods:statementDate ?date .
    ?parent foaf:name ?parentName .
    ?child foaf:name ?childName .
    ?interest rdfs:subPropertyOf bods:hasInterestIn .

    # Only list entities
    ?parent rdf:type bods:Entity .

    FILTER ((?date >= "2020-09-01"^^xsd:date) && (?date < "2020-10-01"^^xsd:date))
}
LIMIT 100
